/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GovUKPayApiClient.Client;
using GovUKPayApiClient.Api;
// uncomment below to import models
//using GovUKPayApiClient.Model;

namespace GovUKPayApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing AuthoriseCardPaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AuthoriseCardPaymentsApiTests : IDisposable
    {
        private AuthoriseCardPaymentsApi instance;

        public AuthoriseCardPaymentsApiTests()
        {
            instance = new AuthoriseCardPaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthoriseCardPaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AuthoriseCardPaymentsApi
            //Assert.IsType<AuthoriseCardPaymentsApi>(instance);
        }

        /// <summary>
        /// Test AuthoriseAMOTOPayment
        /// </summary>
        [Fact]
        public void AuthoriseAMOTOPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthorisationRequest authorisationRequest = null;
            //instance.AuthoriseAMOTOPayment(authorisationRequest);
        }
    }
}
