/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GovUKPayApiClient.Client;
using GovUKPayApiClient.Api;
// uncomment below to import models
//using GovUKPayApiClient.Model;

namespace GovUKPayApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing RefundingCardPaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RefundingCardPaymentsApiTests : IDisposable
    {
        private RefundingCardPaymentsApi instance;

        public RefundingCardPaymentsApiTests()
        {
            instance = new RefundingCardPaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RefundingCardPaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RefundingCardPaymentsApi
            //Assert.IsType<RefundingCardPaymentsApi>(instance);
        }

        /// <summary>
        /// Test GetAPaymentRefund
        /// </summary>
        [Fact]
        public void GetAPaymentRefundTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string paymentId = null;
            //string refundId = null;
            //var response = instance.GetAPaymentRefund(paymentId, refundId);
            //Assert.IsType<Refund>(response);
        }

        /// <summary>
        /// Test GetAllRefundsForAPayment
        /// </summary>
        [Fact]
        public void GetAllRefundsForAPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string paymentId = null;
            //var response = instance.GetAllRefundsForAPayment(paymentId);
            //Assert.IsType<RefundForSearchResult>(response);
        }

        /// <summary>
        /// Test SearchRefunds
        /// </summary>
        [Fact]
        public void SearchRefundsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fromDate = null;
            //string toDate = null;
            //string fromSettledDate = null;
            //string toSettledDate = null;
            //string page = null;
            //string displaySize = null;
            //var response = instance.SearchRefunds(fromDate, toDate, fromSettledDate, toSettledDate, page, displaySize);
            //Assert.IsType<RefundSearchResults>(response);
        }

        /// <summary>
        /// Test SubmitARefundForAPayment
        /// </summary>
        [Fact]
        public void SubmitARefundForAPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string paymentId = null;
            //PaymentRefundRequest paymentRefundRequest = null;
            //var response = instance.SubmitARefundForAPayment(paymentId, paymentRefundRequest);
            //Assert.IsType<Refund>(response);
        }
    }
}
