/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GovUKPayApiClient.Client.OpenAPIDateConverter;

namespace GovUKPayApiClient.Model
{
    /// <summary>
    /// Object containing information about the authentication of the payment.
    /// </summary>
    [DataContract(Name = "AuthorisationSummary")]
    public partial class AuthorisationSummary : IEquatable<AuthorisationSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorisationSummary" /> class.
        /// </summary>
        /// <param name="threeDSecure">threeDSecure.</param>
        public AuthorisationSummary(ThreeDSecure threeDSecure = default(ThreeDSecure))
        {
            this.ThreeDSecure = threeDSecure;
        }

        /// <summary>
        /// Gets or Sets ThreeDSecure
        /// </summary>
        [DataMember(Name = "three_d_secure", EmitDefaultValue = false)]
        public ThreeDSecure ThreeDSecure { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthorisationSummary {\n");
            sb.Append("  ThreeDSecure: ").Append(ThreeDSecure).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthorisationSummary);
        }

        /// <summary>
        /// Returns true if AuthorisationSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthorisationSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorisationSummary input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ThreeDSecure == input.ThreeDSecure ||
                    (this.ThreeDSecure != null &&
                    this.ThreeDSecure.Equals(input.ThreeDSecure))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ThreeDSecure != null)
                {
                    hashCode = (hashCode * 59) + this.ThreeDSecure.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
