/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GovUKPayApiClient.Client.OpenAPIDateConverter;

namespace GovUKPayApiClient.Model
{
    /// <summary>
    /// DisputesSearchResults
    /// </summary>
    [DataContract(Name = "DisputesSearchResults")]
    public partial class DisputesSearchResults : IEquatable<DisputesSearchResults>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputesSearchResults" /> class.
        /// </summary>
        /// <param name="count">Number of disputes on the current page of search results..</param>
        /// <param name="links">links.</param>
        /// <param name="page">The page of results you’re viewing. To view other pages, make this request again using the &#39;page&#39; parameter..</param>
        /// <param name="results">Contains disputes matching your search criteria..</param>
        /// <param name="total">Number of total disputes matching your search criteria..</param>
        public DisputesSearchResults(int count = default(int), SearchNavigationLinks links = default(SearchNavigationLinks), int page = default(int), List<DisputeDetailForSearch> results = default(List<DisputeDetailForSearch>), int total = default(int))
        {
            this.Count = count;
            this.Links = links;
            this.Page = page;
            this.Results = results;
            this.Total = total;
        }

        /// <summary>
        /// Number of disputes on the current page of search results.
        /// </summary>
        /// <value>Number of disputes on the current page of search results.</value>
        [DataMember(Name = "count", EmitDefaultValue = false)]
        public int Count { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", EmitDefaultValue = false)]
        public SearchNavigationLinks Links { get; set; }

        /// <summary>
        /// The page of results you’re viewing. To view other pages, make this request again using the &#39;page&#39; parameter.
        /// </summary>
        /// <value>The page of results you’re viewing. To view other pages, make this request again using the &#39;page&#39; parameter.</value>
        [DataMember(Name = "page", EmitDefaultValue = false)]
        public int Page { get; set; }

        /// <summary>
        /// Contains disputes matching your search criteria.
        /// </summary>
        /// <value>Contains disputes matching your search criteria.</value>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<DisputeDetailForSearch> Results { get; set; }

        /// <summary>
        /// Number of total disputes matching your search criteria.
        /// </summary>
        /// <value>Number of total disputes matching your search criteria.</value>
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DisputesSearchResults {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DisputesSearchResults);
        }

        /// <summary>
        /// Returns true if DisputesSearchResults instances are equal
        /// </summary>
        /// <param name="input">Instance of DisputesSearchResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DisputesSearchResults input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Count == input.Count ||
                    this.Count.Equals(input.Count)
                ) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                ) && 
                (
                    this.Page == input.Page ||
                    this.Page.Equals(input.Page)
                ) && 
                (
                    this.Results == input.Results ||
                    this.Results != null &&
                    input.Results != null &&
                    this.Results.SequenceEqual(input.Results)
                ) && 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Count.GetHashCode();
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Page.GetHashCode();
                if (this.Results != null)
                {
                    hashCode = (hashCode * 59) + this.Results.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Total.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
