/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GovUKPayApiClient.Client.OpenAPIDateConverter;

namespace GovUKPayApiClient.Model
{
    /// <summary>
    /// A structure representing the refunds availability
    /// </summary>
    [DataContract(Name = "RefundSummary")]
    public partial class RefundSummary : IEquatable<RefundSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundSummary" /> class.
        /// </summary>
        /// <param name="status">Availability status of the refund.</param>
        public RefundSummary(string status = default(string))
        {
            this.Status = status;
        }

        /// <summary>
        /// Amount available for refund in pence
        /// </summary>
        /// <value>Amount available for refund in pence</value>
        [DataMember(Name = "amount_available", EmitDefaultValue = false)]
        public long AmountAvailable { get; private set; }

        /// <summary>
        /// Returns false as AmountAvailable should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAmountAvailable()
        {
            return false;
        }
        /// <summary>
        /// Amount submitted for refunds on this Payment in pence
        /// </summary>
        /// <value>Amount submitted for refunds on this Payment in pence</value>
        [DataMember(Name = "amount_submitted", EmitDefaultValue = false)]
        public long AmountSubmitted { get; private set; }

        /// <summary>
        /// Returns false as AmountSubmitted should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAmountSubmitted()
        {
            return false;
        }
        /// <summary>
        /// Availability status of the refund
        /// </summary>
        /// <value>Availability status of the refund</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefundSummary {\n");
            sb.Append("  AmountAvailable: ").Append(AmountAvailable).Append("\n");
            sb.Append("  AmountSubmitted: ").Append(AmountSubmitted).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RefundSummary);
        }

        /// <summary>
        /// Returns true if RefundSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of RefundSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RefundSummary input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AmountAvailable == input.AmountAvailable ||
                    this.AmountAvailable.Equals(input.AmountAvailable)
                ) && 
                (
                    this.AmountSubmitted == input.AmountSubmitted ||
                    this.AmountSubmitted.Equals(input.AmountSubmitted)
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.AmountAvailable.GetHashCode();
                hashCode = (hashCode * 59) + this.AmountSubmitted.GetHashCode();
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
