/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AuthorisationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthorisationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthorisationRequest
        //private AuthorisationRequest instance;

        public AuthorisationRequestTests()
        {
            // TODO uncomment below to create an instance of AuthorisationRequest
            //instance = new AuthorisationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthorisationRequest
        /// </summary>
        [Fact]
        public void AuthorisationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthorisationRequest
            //Assert.IsType<AuthorisationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Fact]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CardholderName'
        /// </summary>
        [Fact]
        public void CardholderNameTest()
        {
            // TODO unit test for the property 'CardholderName'
        }
        /// <summary>
        /// Test the property 'Cvc'
        /// </summary>
        [Fact]
        public void CvcTest()
        {
            // TODO unit test for the property 'Cvc'
        }
        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Fact]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }
        /// <summary>
        /// Test the property 'OneTimeToken'
        /// </summary>
        [Fact]
        public void OneTimeTokenTest()
        {
            // TODO unit test for the property 'OneTimeToken'
        }

    }

}
