/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AuthorisationSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthorisationSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthorisationSummary
        //private AuthorisationSummary instance;

        public AuthorisationSummaryTests()
        {
            // TODO uncomment below to create an instance of AuthorisationSummary
            //instance = new AuthorisationSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthorisationSummary
        /// </summary>
        [Fact]
        public void AuthorisationSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthorisationSummary
            //Assert.IsType<AuthorisationSummary>(instance);
        }


        /// <summary>
        /// Test the property 'ThreeDSecure'
        /// </summary>
        [Fact]
        public void ThreeDSecureTest()
        {
            // TODO unit test for the property 'ThreeDSecure'
        }

    }

}
