/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CardDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardDetails
        //private CardDetails instance;

        public CardDetailsTests()
        {
            // TODO uncomment below to create an instance of CardDetails
            //instance = new CardDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardDetails
        /// </summary>
        [Fact]
        public void CardDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardDetails
            //Assert.IsType<CardDetails>(instance);
        }


        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'CardBrand'
        /// </summary>
        [Fact]
        public void CardBrandTest()
        {
            // TODO unit test for the property 'CardBrand'
        }
        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [Fact]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }
        /// <summary>
        /// Test the property 'CardholderName'
        /// </summary>
        [Fact]
        public void CardholderNameTest()
        {
            // TODO unit test for the property 'CardholderName'
        }
        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Fact]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }
        /// <summary>
        /// Test the property 'FirstDigitsCardNumber'
        /// </summary>
        [Fact]
        public void FirstDigitsCardNumberTest()
        {
            // TODO unit test for the property 'FirstDigitsCardNumber'
        }
        /// <summary>
        /// Test the property 'LastDigitsCardNumber'
        /// </summary>
        [Fact]
        public void LastDigitsCardNumberTest()
        {
            // TODO unit test for the property 'LastDigitsCardNumber'
        }

    }

}
