/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCardPaymentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCardPaymentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCardPaymentRequest
        //private CreateCardPaymentRequest instance;

        public CreateCardPaymentRequestTests()
        {
            // TODO uncomment below to create an instance of CreateCardPaymentRequest
            //instance = new CreateCardPaymentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCardPaymentRequest
        /// </summary>
        [Fact]
        public void CreateCardPaymentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCardPaymentRequest
            //Assert.IsType<CreateCardPaymentRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DelayedCapture'
        /// </summary>
        [Fact]
        public void DelayedCaptureTest()
        {
            // TODO unit test for the property 'DelayedCapture'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Moto'
        /// </summary>
        [Fact]
        public void MotoTest()
        {
            // TODO unit test for the property 'Moto'
        }
        /// <summary>
        /// Test the property 'PrefilledCardholderDetails'
        /// </summary>
        [Fact]
        public void PrefilledCardholderDetailsTest()
        {
            // TODO unit test for the property 'PrefilledCardholderDetails'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

    }

}
