/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePaymentResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePaymentResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePaymentResult
        //private CreatePaymentResult instance;

        public CreatePaymentResultTests()
        {
            // TODO uncomment below to create an instance of CreatePaymentResult
            //instance = new CreatePaymentResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePaymentResult
        /// </summary>
        [Fact]
        public void CreatePaymentResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePaymentResult
            //Assert.IsType<CreatePaymentResult>(instance);
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CardDetails'
        /// </summary>
        [Fact]
        public void CardDetailsTest()
        {
            // TODO unit test for the property 'CardDetails'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'DelayedCapture'
        /// </summary>
        [Fact]
        public void DelayedCaptureTest()
        {
            // TODO unit test for the property 'DelayedCapture'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Moto'
        /// </summary>
        [Fact]
        public void MotoTest()
        {
            // TODO unit test for the property 'Moto'
        }
        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }
        /// <summary>
        /// Test the property 'PaymentProvider'
        /// </summary>
        [Fact]
        public void PaymentProviderTest()
        {
            // TODO unit test for the property 'PaymentProvider'
        }
        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'RefundSummary'
        /// </summary>
        [Fact]
        public void RefundSummaryTest()
        {
            // TODO unit test for the property 'RefundSummary'
        }
        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }
        /// <summary>
        /// Test the property 'SettlementSummary'
        /// </summary>
        [Fact]
        public void SettlementSummaryTest()
        {
            // TODO unit test for the property 'SettlementSummary'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
