/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DisputeLinksForSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisputeLinksForSearchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisputeLinksForSearch
        //private DisputeLinksForSearch instance;

        public DisputeLinksForSearchTests()
        {
            // TODO uncomment below to create an instance of DisputeLinksForSearch
            //instance = new DisputeLinksForSearch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisputeLinksForSearch
        /// </summary>
        [Fact]
        public void DisputeLinksForSearchInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisputeLinksForSearch
            //Assert.IsType<DisputeLinksForSearch>(instance);
        }


        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Fact]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }

    }

}
