/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DisputeDetailForSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisputeDetailForSearchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisputeDetailForSearch
        //private DisputeDetailForSearch instance;

        public DisputeDetailForSearchTests()
        {
            // TODO uncomment below to create an instance of DisputeDetailForSearch
            //instance = new DisputeDetailForSearch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisputeDetailForSearch
        /// </summary>
        [Fact]
        public void DisputeDetailForSearchInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisputeDetailForSearch
            //Assert.IsType<DisputeDetailForSearch>(instance);
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'DisputeId'
        /// </summary>
        [Fact]
        public void DisputeIdTest()
        {
            // TODO unit test for the property 'DisputeId'
        }
        /// <summary>
        /// Test the property 'EvidenceDueDate'
        /// </summary>
        [Fact]
        public void EvidenceDueDateTest()
        {
            // TODO unit test for the property 'EvidenceDueDate'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'NetAmount'
        /// </summary>
        [Fact]
        public void NetAmountTest()
        {
            // TODO unit test for the property 'NetAmount'
        }
        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'SettlementSummary'
        /// </summary>
        [Fact]
        public void SettlementSummaryTest()
        {
            // TODO unit test for the property 'SettlementSummary'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
