/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DisputesSearchResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisputesSearchResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisputesSearchResults
        //private DisputesSearchResults instance;

        public DisputesSearchResultsTests()
        {
            // TODO uncomment below to create an instance of DisputesSearchResults
            //instance = new DisputesSearchResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisputesSearchResults
        /// </summary>
        [Fact]
        public void DisputesSearchResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisputesSearchResults
            //Assert.IsType<DisputesSearchResults>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
