/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalMetadata
        //private ExternalMetadata instance;

        public ExternalMetadataTests()
        {
            // TODO uncomment below to create an instance of ExternalMetadata
            //instance = new ExternalMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalMetadata
        /// </summary>
        [Fact]
        public void ExternalMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalMetadata
            //Assert.IsType<ExternalMetadata>(instance);
        }


        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
