/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentEvent
        //private PaymentEvent instance;

        public PaymentEventTests()
        {
            // TODO uncomment below to create an instance of PaymentEvent
            //instance = new PaymentEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentEvent
        /// </summary>
        [Fact]
        public void PaymentEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentEvent
            //Assert.IsType<PaymentEvent>(instance);
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

    }

}
