/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentLinksForEvents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentLinksForEventsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentLinksForEvents
        //private PaymentLinksForEvents instance;

        public PaymentLinksForEventsTests()
        {
            // TODO uncomment below to create an instance of PaymentLinksForEvents
            //instance = new PaymentLinksForEvents();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentLinksForEvents
        /// </summary>
        [Fact]
        public void PaymentLinksForEventsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentLinksForEvents
            //Assert.IsType<PaymentLinksForEvents>(instance);
        }


        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Fact]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }

    }

}
