/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentLinks
        //private PaymentLinks instance;

        public PaymentLinksTests()
        {
            // TODO uncomment below to create an instance of PaymentLinks
            //instance = new PaymentLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentLinks
        /// </summary>
        [Fact]
        public void PaymentLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentLinks
            //Assert.IsType<PaymentLinks>(instance);
        }


        /// <summary>
        /// Test the property 'AuthUrlPost'
        /// </summary>
        [Fact]
        public void AuthUrlPostTest()
        {
            // TODO unit test for the property 'AuthUrlPost'
        }
        /// <summary>
        /// Test the property 'Cancel'
        /// </summary>
        [Fact]
        public void CancelTest()
        {
            // TODO unit test for the property 'Cancel'
        }
        /// <summary>
        /// Test the property 'Capture'
        /// </summary>
        [Fact]
        public void CaptureTest()
        {
            // TODO unit test for the property 'Capture'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'NextUrl'
        /// </summary>
        [Fact]
        public void NextUrlTest()
        {
            // TODO unit test for the property 'NextUrl'
        }
        /// <summary>
        /// Test the property 'NextUrlPost'
        /// </summary>
        [Fact]
        public void NextUrlPostTest()
        {
            // TODO unit test for the property 'NextUrlPost'
        }
        /// <summary>
        /// Test the property 'Refunds'
        /// </summary>
        [Fact]
        public void RefundsTest()
        {
            // TODO unit test for the property 'Refunds'
        }
        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Fact]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }

    }

}
