/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Refund
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RefundTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Refund
        //private Refund instance;

        public RefundTests()
        {
            // TODO uncomment below to create an instance of Refund
            //instance = new Refund();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Refund
        /// </summary>
        [Fact]
        public void RefundInstanceTest()
        {
            // TODO uncomment below to test "IsType" Refund
            //Assert.IsType<Refund>(instance);
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'RefundId'
        /// </summary>
        [Fact]
        public void RefundIdTest()
        {
            // TODO unit test for the property 'RefundId'
        }
        /// <summary>
        /// Test the property 'SettlementSummary'
        /// </summary>
        [Fact]
        public void SettlementSummaryTest()
        {
            // TODO unit test for the property 'SettlementSummary'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
