/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SearchNavigationLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchNavigationLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchNavigationLinks
        //private SearchNavigationLinks instance;

        public SearchNavigationLinksTests()
        {
            // TODO uncomment below to create an instance of SearchNavigationLinks
            //instance = new SearchNavigationLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchNavigationLinks
        /// </summary>
        [Fact]
        public void SearchNavigationLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchNavigationLinks
            //Assert.IsType<SearchNavigationLinks>(instance);
        }


        /// <summary>
        /// Test the property 'FirstPage'
        /// </summary>
        [Fact]
        public void FirstPageTest()
        {
            // TODO unit test for the property 'FirstPage'
        }
        /// <summary>
        /// Test the property 'LastPage'
        /// </summary>
        [Fact]
        public void LastPageTest()
        {
            // TODO unit test for the property 'LastPage'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'PrevPage'
        /// </summary>
        [Fact]
        public void PrevPageTest()
        {
            // TODO unit test for the property 'PrevPage'
        }
        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Fact]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }

    }

}
