/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SettlementSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettlementSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SettlementSummary
        //private SettlementSummary instance;

        public SettlementSummaryTests()
        {
            // TODO uncomment below to create an instance of SettlementSummary
            //instance = new SettlementSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettlementSummary
        /// </summary>
        [Fact]
        public void SettlementSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" SettlementSummary
            //Assert.IsType<SettlementSummary>(instance);
        }


        /// <summary>
        /// Test the property 'SettledDate'
        /// </summary>
        [Fact]
        public void SettledDateTest()
        {
            // TODO unit test for the property 'SettledDate'
        }

    }

}
