/*
 * GOV.UK Pay API
 *
 * GOV.UK Pay API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GovUKPayApiClient.Api;
using GovUKPayApiClient.Model;
using GovUKPayApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GovUKPayApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ThreeDSecure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThreeDSecureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThreeDSecure
        //private ThreeDSecure instance;

        public ThreeDSecureTests()
        {
            // TODO uncomment below to create an instance of ThreeDSecure
            //instance = new ThreeDSecure();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThreeDSecure
        /// </summary>
        [Fact]
        public void ThreeDSecureInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThreeDSecure
            //Assert.IsType<ThreeDSecure>(instance);
        }


        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

    }

}
